{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chkk-operator.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chkk-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "chkk-operator.annotations" . | nindent 4 }}
type: Opaque
data:
  CHKK_ACCESS_TOKEN: {{ .Values.secret.chkkAccessToken | b64enc }}
{{- end }}