{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chkk-operator.serviceAccountName" . }}
  labels:
    {{- include "chkk-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "chkk-operator.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
